http:
  bind:
    host: 0.0.0.0
    port: 8080

twitter:
  consumer_key: "xYqsf71Dx3IVs94Q1SYT87EEP"
  consumer_secret: "Gh6D6RA4BnNfXVC0qSFmK0O4X8EOQzBA63yoaxin4grr33B5sk"
  access_token_key: "1278330916977418240-S7YkJ074D0uEJ9wPvgY3BI4QT1coNz"
  access_token_secret: "XgKW7chrcrDrvSEmPCDk98Frs60ucOvh3LJUn0saTQ4Du"

counter:
  test:
    name: "My test counter"
    secrets:
      - "asdf"
cache: "cache.json"